apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
   name: complete-devops-project
   namespace: argocd
spec:
  project: default
  source:
     repoURL: "https://github.com/yusuf-anjolaiya/complete-devops-project.git"
     targetRevision: HEAD
     path: complete-devops-project-time-printer
destination:
   server: "https://kubernetes.defaults.svc"
   namespace: default
syncPolicy:
  automated:
   prunet: true
   selfHeal: true